import { getDb } from './index';
import { slugify, generateDoctorSlug } from '../utils/slugify';

// Sample doctor data for testing
const sampleDoctors = [
  {
    npi: '1234567890',
    fullName: 'Dr. Sarah Johnson',
    specialty: 'Cardiology',
    subSpecialty: 'Interventional Cardiology',
    practiceName: 'Austin Heart Center',
    website: 'https://austinheartcenter.com',
    city: 'Austin',
    state: 'TX',
    email: 'sarah.johnson@austinheart.com',
    phone: '(512) 555-0123',
    linkedin: 'https://linkedin.com/in/drsarahjohnson',
    profileStatus: 'Active',
    isVerified: true,
    isFeatured: true,
    priority: 90,
  },
  {
    npi: '2345678901',
    fullName: 'Dr. Michael Chen',
    specialty: 'Neurology',
    subSpecialty: '',
    practiceName: 'Brain & Spine Institute',
    website: 'https://brainspineinstitute.com',
    city: 'Houston',
    state: 'TX',
    email: 'mchen@brainspine.com',
    phone: '(713) 555-0456',
    linkedin: '',
    profileStatus: 'Active',
    isVerified: true,
    isFeatured: false,
    priority: 70,
  },
  {
    npi: '3456789012',
    fullName: 'Dr. Emily Rodriguez',
    specialty: 'Pediatrics',
    subSpecialty: 'Neonatal Care',
    practiceName: "Children's Medical Center",
    website: 'https://childrensmedical.com',
    city: 'Dallas',
    state: 'TX',
    email: 'emily@childrensmed.com',
    phone: '(214) 555-0789',
    linkedin: 'https://linkedin.com/in/dremilyrodriguez',
    profileStatus: 'Active',
    isVerified: true,
    isFeatured: true,
    priority: 85,
  },
  {
    npi: '4567890123',
    fullName: 'Dr. James Wilson',
    specialty: 'Orthopedics',
    subSpecialty: 'Sports Medicine',
    practiceName: 'Texas Orthopedic Specialists',
    website: 'https://texasortho.com',
    city: 'Austin',
    state: 'TX',
    email: 'jwilson@texasortho.com',
    phone: '(512) 555-0234',
    linkedin: '',
    profileStatus: 'Active',
    isVerified: true,
    isFeatured: false,
    priority: 75,
  },
  {
    npi: '5678901234',
    fullName: 'Dr. Amanda Lee',
    specialty: 'Dermatology',
    subSpecialty: 'Cosmetic Dermatology',
    practiceName: 'Clear Skin Clinic',
    website: 'https://clearskinclinic.com',
    city: 'San Antonio',
    state: 'TX',
    email: 'alee@clearskin.com',
    phone: '(210) 555-0345',
    linkedin: 'https://linkedin.com/in/dramandalee',
    profileStatus: 'Active',
    isVerified: true,
    isFeatured: true,
    priority: 80,
  },
  {
    npi: '6789012345',
    fullName: 'Dr. Robert Kim',
    specialty: 'Cardiology',
    subSpecialty: 'Electrophysiology',
    practiceName: 'Houston Heart Rhythm',
    website: 'https://houstonheartrhythm.com',
    city: 'Houston',
    state: 'TX',
    email: 'rkim@houstonheart.com',
    phone: '(713) 555-0567',
    linkedin: '',
    profileStatus: 'Active',
    isVerified: false,
    isFeatured: false,
    priority: 60,
  },
  {
    npi: '7890123456',
    fullName: 'Dr. Jennifer Martinez',
    specialty: 'Internal Medicine',
    subSpecialty: '',
    practiceName: 'Primary Care Associates',
    website: 'https://primarycareaustin.com',
    city: 'Austin',
    state: 'TX',
    email: 'jmartinez@primarycare.com',
    phone: '(512) 555-0678',
    linkedin: 'https://linkedin.com/in/drjennifermartinez',
    profileStatus: 'Active',
    isVerified: true,
    isFeatured: false,
    priority: 65,
  },
  {
    npi: '8901234567',
    fullName: 'Dr. David Park',
    specialty: 'Ophthalmology',
    subSpecialty: 'Retina Specialist',
    practiceName: 'Texas Eye Associates',
    website: 'https://texaseye.com',
    city: 'Dallas',
    state: 'TX',
    email: 'dpark@texaseye.com',
    phone: '(214) 555-0890',
    linkedin: '',
    profileStatus: 'Active',
    isVerified: true,
    isFeatured: true,
    priority: 88,
  },
  {
    npi: '9012345678',
    fullName: 'Dr. Lisa Thompson',
    specialty: 'Psychiatry',
    subSpecialty: 'Child & Adolescent',
    practiceName: 'Mind Wellness Center',
    website: 'https://mindwellness.com',
    city: 'Austin',
    state: 'TX',
    email: 'lthompson@mindwellness.com',
    phone: '(512) 555-0901',
    linkedin: 'https://linkedin.com/in/drlisathompson',
    profileStatus: 'Active',
    isVerified: true,
    isFeatured: false,
    priority: 72,
  },
  {
    npi: '0123456789',
    fullName: 'Dr. Christopher Brown',
    specialty: 'Oncology',
    subSpecialty: 'Breast Cancer',
    practiceName: 'Texas Cancer Center',
    website: 'https://texascancercenter.com',
    city: 'Houston',
    state: 'TX',
    email: 'cbrown@texascancer.com',
    phone: '(713) 555-0012',
    linkedin: '',
    profileStatus: 'Active',
    isVerified: true,
    isFeatured: true,
    priority: 92,
  },
  {
    npi: '1122334455',
    fullName: 'Dr. Michelle Davis',
    specialty: 'Gastroenterology',
    subSpecialty: '',
    practiceName: 'Digestive Health Center',
    website: 'https://digestivehealth.com',
    city: 'San Antonio',
    state: 'TX',
    email: 'mdavis@digestivehealth.com',
    phone: '(210) 555-0123',
    linkedin: '',
    profileStatus: 'Active',
    isVerified: true,
    isFeatured: false,
    priority: 68,
  },
  {
    npi: '2233445566',
    fullName: 'Dr. Andrew Taylor',
    specialty: 'Pulmonology',
    subSpecialty: 'Critical Care',
    practiceName: 'Lung & Breathing Center',
    website: 'https://lungcenter.com',
    city: 'Dallas',
    state: 'TX',
    email: 'ataylor@lungcenter.com',
    phone: '(214) 555-0234',
    linkedin: 'https://linkedin.com/in/drandrewtaylor',
    profileStatus: 'Active',
    isVerified: false,
    isFeatured: false,
    priority: 55,
  },
  {
    npi: '3344556677',
    fullName: 'Dr. Susan White',
    specialty: 'Endocrinology',
    subSpecialty: 'Diabetes Management',
    practiceName: 'Hormone Health Clinic',
    website: 'https://hormonehealth.com',
    city: 'Austin',
    state: 'TX',
    email: 'swhite@hormonehealth.com',
    phone: '(512) 555-0345',
    linkedin: '',
    profileStatus: 'Active',
    isVerified: true,
    isFeatured: false,
    priority: 70,
  },
  {
    npi: '4455667788',
    fullName: 'Dr. Kevin Anderson',
    specialty: 'Urology',
    subSpecialty: '',
    practiceName: 'Texas Urology Group',
    website: 'https://texasurology.com',
    city: 'Houston',
    state: 'TX',
    email: 'kanderson@texasurology.com',
    phone: '(713) 555-0456',
    linkedin: '',
    profileStatus: 'Active',
    isVerified: true,
    isFeatured: false,
    priority: 62,
  },
  {
    npi: '5566778899',
    fullName: 'Dr. Rachel Green',
    specialty: 'Rheumatology',
    subSpecialty: 'Autoimmune Disorders',
    practiceName: 'Joint Care Specialists',
    website: 'https://jointcare.com',
    city: 'San Antonio',
    state: 'TX',
    email: 'rgreen@jointcare.com',
    phone: '(210) 555-0567',
    linkedin: 'https://linkedin.com/in/drrachelgreen',
    profileStatus: 'Active',
    isVerified: true,
    isFeatured: true,
    priority: 78,
  },
];

export function seedDatabase() {
  const db = getDb();

  console.log('Seeding database with sample data...');

  // Clear existing data
  db.exec('DELETE FROM doctors');

  // Insert sample doctors
  const insertStmt = db.prepare(`
    INSERT INTO doctors (
      npi, full_name, slug, specialty, specialty_slug, sub_specialty,
      practice_name, website, city, city_slug, state, state_slug,
      email, phone, linkedin, profile_status, is_verified, is_featured, priority
    ) VALUES (
      @npi, @fullName, @slug, @specialty, @specialtySlug, @subSpecialty,
      @practiceName, @website, @city, @citySlug, @state, @stateSlug,
      @email, @phone, @linkedin, @profileStatus, @isVerified, @isFeatured, @priority
    )
  `);

  for (const doctor of sampleDoctors) {
    const slug = generateDoctorSlug(doctor.fullName, doctor.npi);
    const specialtySlug = slugify(doctor.specialty);
    const citySlug = slugify(doctor.city);
    const stateSlug = doctor.state.toLowerCase();

    insertStmt.run({
      npi: doctor.npi,
      fullName: doctor.fullName,
      slug,
      specialty: doctor.specialty,
      specialtySlug,
      subSpecialty: doctor.subSpecialty || null,
      practiceName: doctor.practiceName || null,
      website: doctor.website || null,
      city: doctor.city,
      citySlug,
      state: doctor.state,
      stateSlug,
      email: doctor.email || null,
      phone: doctor.phone || null,
      linkedin: doctor.linkedin || null,
      profileStatus: doctor.profileStatus,
      isVerified: doctor.isVerified ? 1 : 0,
      isFeatured: doctor.isFeatured ? 1 : 0,
      priority: doctor.priority,
    });
  }

  console.log(`Inserted ${sampleDoctors.length} sample doctors.`);

  return { count: sampleDoctors.length };
}

// Run if called directly
if (require.main === module) {
  seedDatabase();
}
